---
- name: Install the logwatch packages in Redhat derivatives
  yum: name=logwatch state=present
  when: ansible_os_family == 'RedHat'
  tags: [ 'package', 'logwatch' ]

- name: Install the logwatch packages in Debian derivatives
  apt: name=logwatch state=present
  when: ansible_os_family == 'Debian'
  tags: [ 'package', 'logwatch' ]

- name: Configure logwatch
  template: src=logwatch.conf.j2 dest=/etc/logwatch/conf/logwatch.conf
  tags: [ 'configuration', 'package', 'logwatch' ]

- name: Move logwatch script from cron.daily to cron.weekly
  shell: mv /etc/cron.daily/*logwatch /etc/cron.weekly/ removes="/etc/cron.daily/*logwatch"
  when: logwatch_run_weekly